# Documentation:
# https://git-scm.com/docs/git-clone
# https://docs.gitlab.com/ee/ci/variables/predefined_variables.html#predefined-variables-reference
# https://docs.gitlab.com/ee/user/packages/container_registry/
# https://docs.gitlab.com/ee/ci/large_repositories/

# Setting repo variables
variables:
  REPO_TO_CLONE: "https://github.com/torvalds/linux.git"
  CACHE_IMAGE_NAME: cloned_cached_repo_image
  CACHE_FOLDER: linux_kernel_cache

imageBuild:
  image: docker
  stage: build
  services:
    - docker:dind
  before_script:
    # Logging into GitLab Docker registry
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # Setting repo variables on Dockerfile
    - sed -i "s|{{CACHE_FOLDER}}|$CACHE_FOLDER|g" Dockerfile
    - sed -i "s|{{REPO_TO_CLONE}}|$REPO_TO_CLONE|g" Dockerfile
    # Building the image, cloning the repo and its history
    - docker build -f Dockerfile -t $CI_REGISTRY/$CI_PROJECT_PATH/$CACHE_IMAGE_NAME:latest .
    # Pushing the image to GitLab Docker registry
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/$CACHE_IMAGE_NAME:latest
