# Documentation:
# https://docs.gitlab.com/ee/ci/variables/predefined_variables.html#predefined-variables-reference
# https://docs.gitlab.com/ee/user/packages/container_registry/

# Setting repo variables
variables:
  CUSTOM_IMAGE_NAME: custom_docker_image


imageBuild:
  image: docker
  stage: build
  services:
    - docker:dind
  before_script:
    # Logging into GitLab Docker registry
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    # Building the custom image
    - docker build -f Dockerfile -t $CI_REGISTRY/$CI_PROJECT_PATH/$CUSTOM_IMAGE_NAME:latest .
    # Pushing the image to GitLab Docker registry
    - docker push $CI_REGISTRY/$CI_PROJECT_PATH/$CUSTOM_IMAGE_NAME:latest
