# Documentation:
# https://docs.gitlab.com/ee/ci/yaml/#artifactspaths
# https://docs.gitlab.com/ee/ci/yaml/#needsartifacts

generating_artifacts:
  stage: build
  script:
      - mkdir some_folder
      - echo "Doing some work" > some_folder/mybinary.txt
  artifacts:
    paths:
      - some_folder/mybinary.txt

using_artifacts:
  stage: build
  script:
      - cat some_folder/mybinary.txt
  needs:
    - job: generating_artifacts
